/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { EventWhereUniqueInput } from "../../event/base/EventWhereUniqueInput";
import { ExhibitorWhereUniqueInput } from "../../exhibitor/base/ExhibitorWhereUniqueInput";
import { ExhibitorListRelationFilter } from "../../exhibitor/base/ExhibitorListRelationFilter";
import { StringFilter } from "../../util/StringFilter";

@InputType()
class BoothWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => EventWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EventWhereUniqueInput)
  @IsOptional()
  @Field(() => EventWhereUniqueInput, {
    nullable: true,
  })
  event?: EventWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ExhibitorWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ExhibitorWhereUniqueInput)
  @IsOptional()
  @Field(() => ExhibitorWhereUniqueInput, {
    nullable: true,
  })
  exhibitor?: ExhibitorWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ExhibitorListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ExhibitorListRelationFilter)
  @IsOptional()
  @Field(() => ExhibitorListRelationFilter, {
    nullable: true,
  })
  exhibitors?: ExhibitorListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;
}

export { BoothWhereInput as BoothWhereInput };
